name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: pip install -r requirements.txt

    - run: pytest

    - run: docker build -t lr-model .

    - run: docker run lr-model